spring:
  application:
    name: orchestrator-service
app:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: ${spring.application.name}-group-id
    topic:
      order-created: "order-created"
      payment-started: "payment-started"
      payment-succeed: "payment-succeed"
      payment-failed : "payment-failed"
      check-inventory: "check-inventory"
      inventory-check-succeed: "inventory-check-succeed"
      inventory-check-failed: "inventory-check-failed"
      order-cancelled: "order-cancelled"
      order-completed: "order-completed"
server:
  port: 8082